/* tslint:disable */
/* eslint-disable */
/**
 * Builder API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TestPayload,
    TestPayloadFromJSON,
    TestPayloadFromJSONTyped,
    TestPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface EditorState
 */
export interface EditorState {
    /**
     * The language of a runnable
     * @type {string}
     * @memberof EditorState
     */
    lang: string;
    /**
     * The source code of a runnable
     * @type {string}
     * @memberof EditorState
     */
    contents: string;
    /**
     * An array of tests
     * @type {Array<TestPayload>}
     * @memberof EditorState
     */
    tests?: Array<TestPayload>;
}

export function EditorStateFromJSON(json: any): EditorState {
    return EditorStateFromJSONTyped(json, false);
}

export function EditorStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditorState {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lang': json['lang'],
        'contents': json['contents'],
        'tests': !exists(json, 'tests') ? undefined : ((json['tests'] as Array<any>).map(TestPayloadFromJSON)),
    };
}

export function EditorStateToJSON(value?: EditorState | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lang': value.lang,
        'contents': value.contents,
        'tests': value.tests === undefined ? undefined : ((value.tests as Array<any>).map(TestPayloadToJSON)),
    };
}

