/* tslint:disable */
/* eslint-disable */
/**
 * Builder API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestPayload
 */
export interface TestPayload {
    /**
     * 
     * @type {string}
     * @memberof TestPayload
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TestPayload
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof TestPayload
     */
    payload: string;
}

export function TestPayloadFromJSON(json: any): TestPayload {
    return TestPayloadFromJSONTyped(json, false);
}

export function TestPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'payload': json['payload'],
    };
}

export function TestPayloadToJSON(value?: TestPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'payload': value.payload,
    };
}

